spring:
   boot:
      admin:
         client:
            url: "http://localhost:8850"
            instance: 
               service-base-url: http://localhost:${server.port}/
management:
   endpoints:
      web:
         exposure:
            include: "*"