spring:
   boot:
      admin:
         client:
            url: "http://localhost:8850"
management:
   endpoints:
      web:
         exposure:
            include: "*"
   endpoint: 
      health:
       show-details: ALWAYS