spring:
   cloud:
      consul:
         host: localhost
         port: 8500
         discovery:
            serviceName: ${spring.application.name}
            instance-id: ${spring.application.name}:${server.port}