spring:
   cloud:
      consul:
         host: localhost
         port: 8500
         discovery:
            serviceName: ${spring.application.name}#注册到  consul的服务名称
            instance-id: ${spring.application.name}:${server.port}