#tomcat
server:
   port: 8849
spring:
   profiles:
      include:
          monitor,consul
   application:
      name: mango-backup
#backup datasource
mango:
   backup:
      datasource:
         host: localhost
         userName: root
         password: root
         database: vue